### ISSUE TITLE
Refined Storage + jetpack autocrafting

### ISSUE THREAD

**Issue by Moobien** [CyberdyneCC/SimplyJetpacks-2#52]
Hey guys i have both Rs and SJ up to date and having issues with autocrafting.

Leadstone: claims that steam dynamo is missing even though pattern is correct. Jetpack must be manually crafted. Basic flux cap can autocraft.

Hardened: claims reactant dynamo and hardened flux capacitor missing. Autocrafting fails even when these 2 items are crafted as it still demands them. Manual crafting works

Reinforced: claims dynamo and flux cap for this tier plus all previous tiers missing.....

I will also post this on the RS github

**Comment by Moobien** [comment]
https://github.com/raoulvdberge/refinedstorage/issues/1605

**Comment by mike7998** [comment]
There is a similar issue with AE2, where it doesn't recognize jetpacks as valid items to be used to autocraft a higher tier one. Yueh added a patch to the next AE2 update, but that might not fix it.

**Comment by Tomson124** [comment]
I just pushed a potential fix or (at least the beginning of a fix) to github, there should be a new build on the jenkins server: http://modmuss50.me:8080/job/SimplyJetpacks-2/job/SimplyJetpacks-2-1.12/
Build 24
Could you please test it, if it fixes the problem (probably with the new RS version)?

**Comment by mike7998** [comment]
the update fixes it with AE2. the jetpacks can now be autocrafted without issue

**Comment by Moobien** [comment]
do I use both files from the jenkins?

**Comment by Tomson124** [comment]
no the one with "-sources" at the end is only for development purposes, you don't need it.

**Comment by Slyklaw** [comment]
This is still an issue with Refined Storage crafting. With Refined Storage, Thermal Expansion/Dynamics, JEI, and Simply Jetpacks 2 (and their dependencies), a crafting recipe for Hardened Jetpack doesn't recognize an actual Leadstone Jetpack nor a Leadstone Jetpack recipe.
